services:
  backend:
    build: 
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "3006:3006"
    volumes:
      - ./frontend:/frontend